server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Recursos estáticos
    location /assets/ {
        try_files $uri =404;
    }

    # Archivos generados por Angular y otros recursos
    location ~* \.(js|css|svg|png|jpg|jpeg|webp|ico|woff|woff2|ttf)$ {
        try_files $uri =404;
    }

    # Angular Router
    location / {
        try_files $uri $uri/ /index.html;
    }
}